# Generated by Django 5.2.12 on 2026-07-08 00:00

from datetime import datetime, timezone as tzone

from django.db import migrations

# when we started recording suspension times
SUSPENDED_ON_ADDED = datetime(2024, 11, 15, 0, 0, 0, 0, tzone.utc)


def backfill_suspended_on(apps, schema_editor):  # pragma: no cover
    Org = apps.get_model("orgs", "Org")
    Incident = apps.get_model("notifications", "Incident")

    def get_ongoing_incident(org_id):
        return Incident.objects.filter(org_id=org_id, incident_type="org:suspended", ended_on=None).first()

    num_updated = 0

    for org in Org.objects.filter(is_suspended=True, suspended_on__isnull=True):
        # ongoing suspension incidents record the actual suspension time - for child orgs suspended via their parent
        # the incident is on the parent
        incident = get_ongoing_incident(org.id)
        if not incident and org.parent_id:
            incident = get_ongoing_incident(org.parent_id)

        if incident:
            org.suspended_on = incident.started_on
        else:
            # fall back to when the org was last modified - which can't be earlier than when it was suspended - but
            # clamp it to when we started recording suspension times as any modification after that can't have been
            # the suspension itself
            org.suspended_on = min(org.modified_on, SUSPENDED_ON_ADDED)

        org.save(update_fields=("suspended_on",))
        num_updated += 1

    if num_updated:
        print(f"Backfilled suspended_on for {num_updated} suspended orgs")

    # clear any stray values on orgs which aren't suspended
    num_cleared = Org.objects.filter(is_suspended=False, suspended_on__isnull=False).update(suspended_on=None)
    if num_cleared:
        print(f"Cleared suspended_on for {num_cleared} non-suspended orgs")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    backfill_suspended_on(apps, None)


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0182_remove_org_country"),
        ("notifications", "0035_squashed"),
    ]

    operations = [
        migrations.RunPython(backfill_suspended_on, migrations.RunPython.noop),
    ]
