# Generated by Django 5.2.14 on 2026-07-13 00:00

from django.db import migrations

# legacy timezone aliases mapped to their canonical IANA names
TIMEZONE_ALIASES = {
    "America/Montreal": "America/Toronto",
    "Canada/Atlantic": "America/Halifax",
    "Canada/Central": "America/Winnipeg",
    "Canada/Eastern": "America/Toronto",
    "Canada/Mountain": "America/Edmonton",
    "Canada/Newfoundland": "America/St_Johns",
    "Canada/Pacific": "America/Vancouver",
    "GMT": "UTC",
    "US/Alaska": "America/Anchorage",
    "US/Arizona": "America/Phoenix",
    "US/Central": "America/Chicago",
    "US/Eastern": "America/New_York",
    "US/Hawaii": "Pacific/Honolulu",
    "US/Mountain": "America/Denver",
    "US/Pacific": "America/Los_Angeles",
}


def normalize_timezones(apps, schema_editor):  # pragma: no cover
    Org = apps.get_model("orgs", "Org")

    for alias, canonical in TIMEZONE_ALIASES.items():
        num_updated = Org.objects.filter(timezone=alias).update(timezone=canonical)
        if num_updated:
            print(f"Updated {num_updated} orgs with timezone {alias} to {canonical}")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    normalize_timezones(apps, None)


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0184_org_orgs_org_suspended_on_consistent"),
    ]

    operations = [
        migrations.RunPython(normalize_timezones, migrations.RunPython.noop),
    ]
