# Generated by Django 6.0.7 on 2026-07-30 15:51

from django.db import migrations

# website languages still supported at the time of this migration
LANGUAGES = ["en-us", "es", "fr", "pt-br"]
DEFAULT_LANGUAGE = "en-us"


def reset_dropped_languages(apps, schema_editor):  # pragma: no cover
    Org = apps.get_model("orgs", "Org")

    # note that language is nullable on orgs so null values are left as they are
    num_updated = Org.objects.exclude(language__in=LANGUAGES).exclude(language=None).update(language=DEFAULT_LANGUAGE)
    if num_updated:
        print(f"Updated {num_updated} orgs with an unsupported language to {DEFAULT_LANGUAGE}")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    reset_dropped_languages(apps, None)


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0187_alter_org_language"),
    ]

    operations = [
        migrations.RunPython(reset_dropped_languages, migrations.RunPython.noop),
    ]
