# Generated by Django 6.1.1 on 2026-09-15 12:00

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0006_helpdeskimport"),
        ("orgs", "0190_org_admin_groups"),
    ]

    operations = [
        migrations.RenameModel(old_name="Knowledge", new_name="KnowledgeSource"),
        migrations.AlterField(
            model_name="knowledgesource",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sources", to="orgs.org"),
        ),
        migrations.RenameField(model_name="knowledgesource", old_name="knowledge_type", new_name="source_type"),
        migrations.RenameField(model_name="article", old_name="knowledge", new_name="source"),
        migrations.RenameField(model_name="helpsite", old_name="knowledge", new_name="source"),
        migrations.RenameField(model_name="helpdeskimport", old_name="knowledge", new_name="source"),
        migrations.RenameField(model_name="knowledgeitem", old_name="knowledge", new_name="source"),
        migrations.RenameField(model_name="knowledgechunk", old_name="knowledge", new_name="source"),
        migrations.RenameIndex(
            model_name="knowledgesource", old_name="knowledge_pending", new_name="knowledgesource_pending"
        ),
        migrations.RemoveConstraint(model_name="knowledgesource", name="unique_knowledge_names"),
        migrations.AddConstraint(
            model_name="knowledgesource",
            constraint=models.UniqueConstraint(
                models.F("org"), django.db.models.functions.text.Lower("name"), name="unique_knowledgesource_names"
            ),
        ),
        # the indexes and constraints over the renamed FKs already exist in the database under the same names and
        # were renamed along with their columns, so only the migration state needs to learn the new field name
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(model_name="article", name="unique_article_slugs"),
                migrations.AddConstraint(
                    model_name="article",
                    constraint=models.UniqueConstraint(
                        models.F("source"),
                        models.F("slug"),
                        condition=models.Q(("is_active", True)),
                        name="unique_article_slugs",
                    ),
                ),
                migrations.RemoveConstraint(model_name="knowledgeitem", name="unique_knowledge_item_urls"),
                migrations.AddConstraint(
                    model_name="knowledgeitem",
                    constraint=models.UniqueConstraint(
                        models.F("source"), models.F("url"), name="unique_knowledge_item_urls"
                    ),
                ),
                migrations.RemoveIndex(model_name="article", name="article_by_tree"),
                migrations.AddIndex(
                    model_name="article",
                    index=models.Index(fields=["source", "parent", "sort_order"], name="article_by_tree"),
                ),
                migrations.RemoveIndex(model_name="article", name="article_by_modified"),
                migrations.AddIndex(
                    model_name="article",
                    index=models.Index(fields=["source", "modified_on"], name="article_by_modified"),
                ),
                migrations.RemoveIndex(model_name="helpdeskimport", name="helpdeskimport_by_created"),
                migrations.AddIndex(
                    model_name="helpdeskimport",
                    index=models.Index(fields=["source", "-created_on"], name="helpdeskimport_by_created"),
                ),
                migrations.RemoveIndex(model_name="knowledgechunk", name="knowledgechunk_by_item"),
                migrations.AddIndex(
                    model_name="knowledgechunk",
                    index=models.Index(fields=["source", "item_key"], name="knowledgechunk_by_item"),
                ),
            ],
        ),
    ]
