# Generated by Django 6.1.1 on 2026-09-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0007_rename_knowledge_knowledgesource"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="body_html",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="article",
            name="headings",
            field=models.JSONField(default=list),
        ),
    ]
