# Generated by Django 6.1.1 on 2026-09-14 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0315_update_triggers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="broadcast",
            name="node_uuid",
        ),
    ]
