# Generated by Django 6.1.1 on 2026-09-14 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0410_remove_flowrun_active_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="flowrun",
            name="flows_flowrun_contacts_at_node",
        ),
    ]
