# Generated by Django 5.2.10 on 2026-01-13 20:03

from datetime import datetime, timezone as tzone

from django.db import migrations


def fix_bad_last_seen_ons(apps, schema_editor):  # pragma: no cover
    Contact = apps.get_model("contacts", "Contact")

    zero_date = datetime(1, 1, 1, 0, 0, tzinfo=tzone.utc)
    num_updated = 0

    while True:
        batch = list(Contact.objects.filter(last_seen_on=zero_date).only("id", "modified_on")[:1000])
        if not batch:
            break

        for contact in batch:
            candidates = []
            if last_msg := contact.msgs.order_by("id").last():
                candidates.append(last_msg.created_on)
            if last_evt := contact.channel_events.order_by("id").last():
                candidates.append(last_evt.created_on)
            # maybe messages/events were deleted, in which case we fall back to modified_on
            if not candidates:
                candidates.append(contact.modified_on)

            contact.last_seen_on = max(candidates)
            contact.modified_on = datetime.now(tzone.utc)  # needed for indexer
            num_updated += 1

        Contact.objects.bulk_update(batch, ["last_seen_on", "modified_on"])
        print(f"Updated {num_updated} contacts with bad last_seen_on values")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    fix_bad_last_seen_ons(apps, None)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("contacts", "0214_alter_contactimport_uuid"),
    ]

    operations = [
        migrations.RunPython(fix_bad_last_seen_ons, migrations.RunPython.noop),
    ]
