# Generated by Django 6.1.1 on 2026-09-29 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0218_alter_contactgroup_uuid"),
        ("flows", "0411_remove_flowrun_contacts_at_node_index"),
        ("orgs", "0190_org_admin_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="email_verified_on",
            field=models.DateTimeField(null=True),
        ),
    ]
