# Generated by Django 6.0.7 on 2026-07-28 21:05

from django.contrib.postgres.operations import AddIndexConcurrently, RemoveIndexConcurrently
from django.db import migrations, models
from django.db.migrations.operations.models import AddIndex, RemoveIndex


class AddIndexConcurrentlyPlainReverse(AddIndexConcurrently):
    """
    Adds the index concurrently but reverses with a plain drop, so that migration tests - which roll the graph
    backwards inside a transaction - can unapply it.
    """

    def database_backwards(self, app_label, schema_editor, from_state, to_state):  # pragma: no cover
        AddIndex.database_backwards(self, app_label, schema_editor, from_state, to_state)


class RemoveIndexConcurrentlyPlainReverse(RemoveIndexConcurrently):
    """
    Removes the index concurrently but reverses with a plain create, so that migration tests - which roll the graph
    backwards inside a transaction - can unapply it.
    """

    def database_backwards(self, app_label, schema_editor, from_state, to_state):  # pragma: no cover
        RemoveIndex.database_backwards(self, app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    # index builds on the tickets table can't take ACCESS EXCLUSIVE for the duration, so the new indexes are
    # created concurrently under their own names before the old ones are dropped concurrently
    atomic = False

    dependencies = [
        ("orgs", "0186_alter_export_id_alter_invitation_id_and_more"),
        ("tickets", "0090_alter_ticket_id"),
    ]

    operations = [
        AddIndexConcurrentlyPlainReverse(
            model_name="ticket",
            index=models.Index(fields=["org", "-status", "-last_activity_on", "-id"], name="tickets_org_status_desc"),
        ),
        AddIndexConcurrentlyPlainReverse(
            model_name="ticket",
            index=models.Index(
                fields=["org", "assignee", "-status", "-last_activity_on", "-id"],
                name="tickets_org_assign_status_desc",
            ),
        ),
        RemoveIndexConcurrentlyPlainReverse(
            model_name="ticket",
            name="tickets_org_status",
        ),
        RemoveIndexConcurrentlyPlainReverse(
            model_name="ticket",
            name="tickets_org_assignee_status",
        ),
    ]
